### ISSUE TITLE
Improve JS Selections

### ISSUE THREAD

**Issue by ricardojsmarques** [ricardfilip/LoL-Legendary#1]
After seeing the "Inefficient jQuery usage" warning in phpStorm, I think its a good idea to implement this at some point in our js.

SO Question  :http://stackoverflow.com/questions/12674591/inefficient-jquery-usage-warnings-in-phpstorm-ide

https://24ways.org/2011/your-jquery-now-with-less-suck/

**Comment by ricardfilip** [comment]
okay sure!

2015-10-21 10:51 GMT+01:00 ddrjm notifications@github.com:
